spring.application.name=student-api
server.port=8088
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:studentApiDb
spring.datasource.username=sa
spring-datasource.passwowrd=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.h2.console.path=/h2-console